---
- name: sysctl | Set sysctl values
  sysctl:
    ignoreerrors: "no"
    reload: "yes"
    state: "present"
    sysctl_file: "{{ hostvars[inventory_hostname]['sysctl_dest'] + '/' + vars['outer_item'] + '.conf' }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ hostvars[inventory_hostname]['sysctl'] | json_query(\"[?file=='\" + vars['outer_item'] + \"'].options\") }}"
  loop_control:
    label: "{{ item.name }}"
