---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "sysctl_executor.yml"
  when:
   - "vars['sysctl_files'] is defined"
   - "vars['sysctl_files'] != []"
   - "vars['sysctl_files'] != ''"
