---
- name: Delete present sysctl files
  file:
    name: "{{ item.file }}"
    state: "absent"
  with_items: "{{ hostvars[inventory_hostname]['sysctl_options'] }}"
- name: Set sysctl values
  sysctl:
    ignoreerrors: "no"
    reload: "yes"
    state: "present"
    sysctl_file: "{{ item.file }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ hostvars[inventory_hostname]['sysctl_options'] }}"
